
name: Label PR by Team
description: Label PR based on team membership

on:
  pull_request:
    # test message13
    types: [opened]

jobs:
  label-pr:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Generate GitHub App Token
          id: app-token
          uses: tibdex/github-app-token@v1
          with:
            app_id: ${{ vars.TAOSDATA_BOT_ID }}
            private_key: ${{ secrets.TAOSDATA_BOT_KEY }}

        - name: AutoCorrect
          uses: huacnlee/autocorrect-action@v2

        - name: Report ReviewDog
          if: failure()
          uses: huacnlee/autocorrect-action@v2
          env : 
            REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            reviewdog: true