
name: Review Dog

on:
  pull_request:
    branches:
      - 'main'
      - '3.0'
jobs:
  reviewdog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4    
      - name: Report ReviewDog
        uses: tomchon/autocorrect-action@fix/review-dog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          reviewdog: true
          args: /github/workspace/docs/zh/*  /github/workspace/docs/en/* 

